twig:
  default_path: "%kernel.project_dir%/templates"
  globals:
    company_name: "%company_name%"
    company_phone: "%company_phone%"
    company_email: "%company_email%"

when@test:
  twig:
    strict_variables: true
